# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Sam Bond-Taylor
email: samuel.e.bond-taylor@dur.ac.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sambondtaylor
github_username:  samb-t
markdown: kramdown
google_site_verification: XGMPMp23r5k2e3ICQN4HJx7-mrggkn3COJEAofH1VUU

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0" 
# theme: minimal-mistakes-jekyll
plugins:
  - jekyll-include-cache
  # - jekyll-feed
  # - jekyll-archives

name: Sam Bond-Taylor
author:
  name: "Sam Bond-Taylor"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Deep Learning PhD student at Durham University."
  links:
    - label: "Durham, UK"
      icon: "fas fa-fw fa-map-marker-alt"
      url: "https://www.durham.ac.uk/staff/samuel-e-bond-taylor/"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:samuel.e.bond-taylor@dur.ac.uk"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sambondtaylor"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/samb-t"
footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:samuel.e.bond-taylor@dur.ac.uk"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sambondtaylor"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/samb-t"
    - label: "Durham Profile"
      icon: "fas fa-fw fa-link"
      url: "https://www.durham.ac.uk/staff/samuel-e-bond-taylor/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true

compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment

include:
  - _pages
atom_feed:
  hide: true


